const availableMessageProps = {
    '1.71': [
        'ui/core/messagebundle',
        'ui/core/designtime/messagebundle',
        'ui/rta/messagebundle',
        'ui/integration/messagebundle',
        'ui/layout/messagebundle',
        'ui/layout/designtime/messagebundle',
        'ui/fl/messagebundle',
        'ui/fl/designtime/messagebundle',
        'ui/unified/messagebundle',
        'ui/unified/designtime/messagebundle',
        'ui/table/messagebundle',
        'ui/table/designtime/messagebundle',
        'uxap/messagebundle',
        'tnt/messagebundle',
        'f/messagebundle',
        'f/designtime/messagebundle',
        'm/messagebundle',
        'm/designtime/messagebundle',
        'ui/core/messagebundle_sk',
        'ui/core/messagebundle_pl',
        'ui/core/messagebundle_th',
        'ui/core/messagebundle_fr',
        'ui/core/messagebundle_en',
        'ui/core/messagebundle_fi',
        'ui/core/messagebundle_ro',
        'ui/core/messagebundle_ja',
        'ui/core/messagebundle_ca',
        'ui/core/messagebundle_uk',
        'ui/core/messagebundle_no',
        'ui/core/messagebundle_de',
        'ui/core/messagebundle_bg',
        'ui/core/messagebundle_ko',
        'ui/core/messagebundle_el',
        'ui/core/messagebundle_ms',
        'ui/core/messagebundle_vi',
        'ui/core/messagebundle_sl',
        'ui/core/messagebundle_iw',
        'ui/core/messagebundle_zh_TW',
        'ui/core/messagebundle_hu',
        'ui/core/messagebundle_cs',
        'ui/core/messagebundle_tr',
        'ui/core/messagebundle_it',
        'ui/core/messagebundle_en_US_sappsd',
        'ui/core/messagebundle_zh_CN',
        'ui/core/messagebundle_lt',
        'ui/core/messagebundle_en_US_saptrc',
        'ui/core/messagebundle_ru',
        'ui/core/messagebundle_es_MX',
        'ui/core/messagebundle_nl',
        'ui/core/messagebundle_et',
        'ui/core/messagebundle_es',
        'ui/core/messagebundle_hi',
        'ui/core/messagebundle_da',
        'ui/core/messagebundle_pt',
        'ui/core/messagebundle_sh',
        'ui/core/messagebundle_lv',
        'ui/core/messagebundle_ar',
        'ui/core/messagebundle_sv',
        'ui/core/messagebundle_kk',
        'ui/core/messagebundle_en_GB',
        'ui/core/messagebundle_hr',
        'ui/rta/messagebundle_sk',
        'ui/rta/messagebundle_pl',
        'ui/rta/messagebundle_th',
        'ui/rta/messagebundle_fr',
        'ui/rta/messagebundle_en',
        'ui/rta/messagebundle_fi',
        'ui/rta/messagebundle_ro',
        'ui/rta/messagebundle_ja',
        'ui/rta/messagebundle_ca',
        'ui/rta/messagebundle_uk',
        'ui/rta/messagebundle_no',
        'ui/rta/messagebundle_de',
        'ui/rta/messagebundle_bg',
        'ui/rta/messagebundle_ko',
        'ui/rta/messagebundle_el',
        'ui/rta/messagebundle_ms',
        'ui/rta/messagebundle_vi',
        'ui/rta/messagebundle_sl',
        'ui/rta/messagebundle_iw',
        'ui/rta/messagebundle_zh_TW',
        'ui/rta/messagebundle_hu',
        'ui/rta/messagebundle_cs',
        'ui/rta/messagebundle_tr',
        'ui/rta/messagebundle_it',
        'ui/rta/messagebundle_en_US_sappsd',
        'ui/rta/messagebundle_zh_CN',
        'ui/rta/messagebundle_lt',
        'ui/rta/messagebundle_en_US_saptrc',
        'ui/rta/messagebundle_ru',
        'ui/rta/messagebundle_es_MX',
        'ui/rta/messagebundle_nl',
        'ui/rta/messagebundle_et',
        'ui/rta/messagebundle_es',
        'ui/rta/messagebundle_hi',
        'ui/rta/messagebundle_da',
        'ui/rta/messagebundle_pt',
        'ui/rta/messagebundle_sh',
        'ui/rta/messagebundle_lv',
        'ui/rta/messagebundle_ar',
        'ui/rta/messagebundle_sv',
        'ui/rta/messagebundle_kk',
        'ui/rta/messagebundle_en_GB',
        'ui/rta/messagebundle_hr',
        'ui/integration/messagebundle_sk',
        'ui/integration/messagebundle_pl',
        'ui/integration/messagebundle_th',
        'ui/integration/messagebundle_fr',
        'ui/integration/messagebundle_en',
        'ui/integration/messagebundle_fi',
        'ui/integration/messagebundle_ro',
        'ui/integration/messagebundle_ja',
        'ui/integration/messagebundle_ca',
        'ui/integration/messagebundle_uk',
        'ui/integration/messagebundle_no',
        'ui/integration/messagebundle_de',
        'ui/integration/messagebundle_bg',
        'ui/integration/messagebundle_ko',
        'ui/integration/messagebundle_el',
        'ui/integration/messagebundle_ms',
        'ui/integration/messagebundle_vi',
        'ui/integration/messagebundle_sl',
        'ui/integration/messagebundle_iw',
        'ui/integration/messagebundle_zh_TW',
        'ui/integration/messagebundle_hu',
        'ui/integration/messagebundle_cs',
        'ui/integration/messagebundle_tr',
        'ui/integration/messagebundle_it',
        'ui/integration/messagebundle_en_US_sappsd',
        'ui/integration/messagebundle_zh_CN',
        'ui/integration/messagebundle_lt',
        'ui/integration/messagebundle_en_US_saptrc',
        'ui/integration/messagebundle_ru',
        'ui/integration/messagebundle_nl',
        'ui/integration/messagebundle_et',
        'ui/integration/messagebundle_es',
        'ui/integration/messagebundle_hi',
        'ui/integration/messagebundle_da',
        'ui/integration/messagebundle_pt',
        'ui/integration/messagebundle_sh',
        'ui/integration/messagebundle_lv',
        'ui/integration/messagebundle_ar',
        'ui/integration/messagebundle_sv',
        'ui/integration/messagebundle_kk',
        'ui/integration/messagebundle_en_GB',
        'ui/integration/messagebundle_hr',
        'ui/layout/messagebundle_sk',
        'ui/layout/messagebundle_pl',
        'ui/layout/messagebundle_th',
        'ui/layout/messagebundle_fr',
        'ui/layout/messagebundle_en',
        'ui/layout/messagebundle_fi',
        'ui/layout/messagebundle_ro',
        'ui/layout/messagebundle_ja',
        'ui/layout/messagebundle_ca',
        'ui/layout/messagebundle_uk',
        'ui/layout/messagebundle_no',
        'ui/layout/messagebundle_de',
        'ui/layout/messagebundle_bg',
        'ui/layout/messagebundle_ko',
        'ui/layout/messagebundle_el',
        'ui/layout/messagebundle_ms',
        'ui/layout/messagebundle_vi',
        'ui/layout/messagebundle_sl',
        'ui/layout/messagebundle_iw',
        'ui/layout/messagebundle_zh_TW',
        'ui/layout/messagebundle_hu',
        'ui/layout/messagebundle_cs',
        'ui/layout/messagebundle_tr',
        'ui/layout/messagebundle_it',
        'ui/layout/messagebundle_en_US_sappsd',
        'ui/layout/messagebundle_zh_CN',
        'ui/layout/messagebundle_lt',
        'ui/layout/messagebundle_en_US_saptrc',
        'ui/layout/messagebundle_ru',
        'ui/layout/messagebundle_es_MX',
        'ui/layout/messagebundle_nl',
        'ui/layout/messagebundle_et',
        'ui/layout/messagebundle_es',
        'ui/layout/messagebundle_hi',
        'ui/layout/messagebundle_da',
        'ui/layout/designtime/messagebundle_sk',
        'ui/layout/designtime/messagebundle_pl',
        'ui/layout/designtime/messagebundle_th',
        'ui/layout/designtime/messagebundle_fr',
        'ui/layout/designtime/messagebundle_en',
        'ui/layout/designtime/messagebundle_fi',
        'ui/layout/designtime/messagebundle_ro',
        'ui/layout/designtime/messagebundle_ja',
        'ui/layout/designtime/messagebundle_ca',
        'ui/layout/designtime/messagebundle_uk',
        'ui/layout/designtime/messagebundle_no',
        'ui/layout/designtime/messagebundle_de',
        'ui/layout/designtime/messagebundle_bg',
        'ui/layout/designtime/messagebundle_ko',
        'ui/layout/designtime/messagebundle_el',
        'ui/layout/designtime/messagebundle_ms',
        'ui/layout/designtime/messagebundle_vi',
        'ui/layout/designtime/messagebundle_sl',
        'ui/layout/designtime/messagebundle_iw',
        'ui/layout/designtime/messagebundle_zh_TW',
        'ui/layout/designtime/messagebundle_hu',
        'ui/layout/designtime/messagebundle_cs',
        'ui/layout/designtime/messagebundle_tr',
        'ui/layout/designtime/messagebundle_it',
        'ui/layout/designtime/messagebundle_en_US_sappsd',
        'ui/layout/designtime/messagebundle_zh_CN',
        'ui/layout/designtime/messagebundle_lt',
        'ui/layout/designtime/messagebundle_en_US_saptrc',
        'ui/layout/designtime/messagebundle_ru',
        'ui/layout/designtime/messagebundle_es_MX',
        'ui/layout/designtime/messagebundle_nl',
        'ui/layout/designtime/messagebundle_et',
        'ui/layout/designtime/messagebundle_es',
        'ui/layout/designtime/messagebundle_hi',
        'ui/layout/designtime/messagebundle_da',
        'ui/layout/designtime/messagebundle_pt',
        'ui/layout/designtime/messagebundle_sh',
        'ui/layout/designtime/messagebundle_lv',
        'ui/layout/designtime/messagebundle_ar',
        'ui/layout/designtime/messagebundle_sv',
        'ui/layout/designtime/messagebundle_kk',
        'ui/layout/designtime/messagebundle_en_GB',
        'ui/layout/designtime/messagebundle_hr',
        'ui/layout/messagebundle_pt',
        'ui/layout/messagebundle_sh',
        'ui/layout/messagebundle_lv',
        'ui/layout/messagebundle_ar',
        'ui/layout/messagebundle_sv',
        'ui/layout/messagebundle_kk',
        'ui/layout/messagebundle_en_GB',
        'ui/layout/messagebundle_hr',
        'ui/fl/messagebundle_sk',
        'ui/fl/messagebundle_pl',
        'ui/fl/messagebundle_th',
        'ui/fl/messagebundle_fr',
        'ui/fl/messagebundle_en',
        'ui/fl/messagebundle_fi',
        'ui/fl/messagebundle_ro',
        'ui/fl/messagebundle_ja',
        'ui/fl/messagebundle_ca',
        'ui/fl/messagebundle_uk',
        'ui/fl/messagebundle_no',
        'ui/fl/messagebundle_de',
        'ui/fl/messagebundle_bg',
        'ui/fl/messagebundle_ko',
        'ui/fl/messagebundle_el',
        'ui/fl/messagebundle_ms',
        'ui/fl/messagebundle_vi',
        'ui/fl/messagebundle_sl',
        'ui/fl/messagebundle_iw',
        'ui/fl/messagebundle_zh_TW',
        'ui/fl/messagebundle_hu',
        'ui/fl/messagebundle_cs',
        'ui/fl/messagebundle_tr',
        'ui/fl/messagebundle_it',
        'ui/fl/messagebundle_en_US_sappsd',
        'ui/fl/messagebundle_zh_CN',
        'ui/fl/messagebundle_lt',
        'ui/fl/messagebundle_en_US_saptrc',
        'ui/fl/messagebundle_ru',
        'ui/fl/messagebundle_es_MX',
        'ui/fl/messagebundle_nl',
        'ui/fl/messagebundle_et',
        'ui/fl/messagebundle_es',
        'ui/fl/messagebundle_hi',
        'ui/fl/messagebundle_da',
        'ui/fl/messagebundle_pt',
        'ui/fl/messagebundle_sh',
        'ui/fl/messagebundle_lv',
        'ui/fl/messagebundle_ar',
        'ui/fl/messagebundle_sv',
        'ui/fl/messagebundle_kk',
        'ui/fl/messagebundle_en_GB',
        'ui/fl/messagebundle_hr',
        'ui/unified/messagebundle_sk',
        'ui/unified/messagebundle_pl',
        'ui/unified/messagebundle_th',
        'ui/unified/messagebundle_fr',
        'ui/unified/messagebundle_en',
        'ui/unified/messagebundle_fi',
        'ui/unified/messagebundle_ro',
        'ui/unified/messagebundle_ja',
        'ui/unified/messagebundle_ca',
        'ui/unified/messagebundle_uk',
        'ui/unified/messagebundle_no',
        'ui/unified/messagebundle_de',
        'ui/unified/messagebundle_bg',
        'ui/unified/messagebundle_ko',
        'ui/unified/messagebundle_el',
        'ui/unified/messagebundle_ms',
        'ui/unified/messagebundle_vi',
        'ui/unified/messagebundle_sl',
        'ui/unified/messagebundle_iw',
        'ui/unified/messagebundle_zh_TW',
        'ui/unified/messagebundle_hu',
        'ui/unified/messagebundle_cs',
        'ui/unified/messagebundle_tr',
        'ui/unified/messagebundle_it',
        'ui/unified/messagebundle_en_US_sappsd',
        'ui/unified/messagebundle_zh_CN',
        'ui/unified/messagebundle_lt',
        'ui/unified/messagebundle_en_US_saptrc',
        'ui/unified/messagebundle_ru',
        'ui/unified/messagebundle_es_MX',
        'ui/unified/messagebundle_nl',
        'ui/unified/messagebundle_et',
        'ui/unified/messagebundle_es',
        'ui/unified/messagebundle_hi',
        'ui/unified/messagebundle_da',
        'ui/unified/designtime/messagebundle_sk',
        'ui/unified/designtime/messagebundle_pl',
        'ui/unified/designtime/messagebundle_th',
        'ui/unified/designtime/messagebundle_fr',
        'ui/unified/designtime/messagebundle_en',
        'ui/unified/designtime/messagebundle_fi',
        'ui/unified/designtime/messagebundle_ro',
        'ui/unified/designtime/messagebundle_ja',
        'ui/unified/designtime/messagebundle_ca',
        'ui/unified/designtime/messagebundle_uk',
        'ui/unified/designtime/messagebundle_no',
        'ui/unified/designtime/messagebundle_de',
        'ui/unified/designtime/messagebundle_bg',
        'ui/unified/designtime/messagebundle_ko',
        'ui/unified/designtime/messagebundle_el',
        'ui/unified/designtime/messagebundle_ms',
        'ui/unified/designtime/messagebundle_vi',
        'ui/unified/designtime/messagebundle_sl',
        'ui/unified/designtime/messagebundle_iw',
        'ui/unified/designtime/messagebundle_zh_TW',
        'ui/unified/designtime/messagebundle_hu',
        'ui/unified/designtime/messagebundle_cs',
        'ui/unified/designtime/messagebundle_tr',
        'ui/unified/designtime/messagebundle_it',
        'ui/unified/designtime/messagebundle_en_US_sappsd',
        'ui/unified/designtime/messagebundle_zh_CN',
        'ui/unified/designtime/messagebundle_lt',
        'ui/unified/designtime/messagebundle_en_US_saptrc',
        'ui/unified/designtime/messagebundle_ru',
        'ui/unified/designtime/messagebundle_es_MX',
        'ui/unified/designtime/messagebundle_nl',
        'ui/unified/designtime/messagebundle_et',
        'ui/unified/designtime/messagebundle_es',
        'ui/unified/designtime/messagebundle_hi',
        'ui/unified/designtime/messagebundle_da',
        'ui/unified/designtime/messagebundle_pt',
        'ui/unified/designtime/messagebundle_sh',
        'ui/unified/designtime/messagebundle_lv',
        'ui/unified/designtime/messagebundle_ar',
        'ui/unified/designtime/messagebundle_sv',
        'ui/unified/designtime/messagebundle_kk',
        'ui/unified/designtime/messagebundle_en_GB',
        'ui/unified/designtime/messagebundle_hr',
        'ui/unified/messagebundle_pt',
        'ui/unified/messagebundle_sh',
        'ui/unified/messagebundle_lv',
        'ui/unified/messagebundle_ar',
        'ui/unified/messagebundle_sv',
        'ui/unified/messagebundle_kk',
        'ui/unified/messagebundle_en_GB',
        'ui/unified/messagebundle_hr',
        'ui/table/messagebundle_sk',
        'ui/table/messagebundle_pl',
        'ui/table/messagebundle_th',
        'ui/table/messagebundle_fr',
        'ui/table/messagebundle_en',
        'ui/table/messagebundle_fi',
        'ui/table/messagebundle_ro',
        'ui/table/messagebundle_ja',
        'ui/table/messagebundle_ca',
        'ui/table/messagebundle_uk',
        'ui/table/messagebundle_no',
        'ui/table/messagebundle_de',
        'ui/table/messagebundle_bg',
        'ui/table/messagebundle_ko',
        'ui/table/messagebundle_el',
        'ui/table/messagebundle_ms',
        'ui/table/messagebundle_vi',
        'ui/table/messagebundle_sl',
        'ui/table/messagebundle_iw',
        'ui/table/messagebundle_zh_TW',
        'ui/table/messagebundle_hu',
        'ui/table/messagebundle_cs',
        'ui/table/messagebundle_tr',
        'ui/table/messagebundle_it',
        'ui/table/messagebundle_en_US_sappsd',
        'ui/table/messagebundle_zh_CN',
        'ui/table/messagebundle_lt',
        'ui/table/messagebundle_en_US_saptrc',
        'ui/table/messagebundle_ru',
        'ui/table/messagebundle_es_MX',
        'ui/table/messagebundle_nl',
        'ui/table/messagebundle_et',
        'ui/table/messagebundle_es',
        'ui/table/messagebundle_hi',
        'ui/table/messagebundle_da',
        'ui/table/messagebundle_pt',
        'ui/table/messagebundle_sh',
        'ui/table/messagebundle_lv',
        'ui/table/messagebundle_ar',
        'ui/table/messagebundle_sv',
        'ui/table/messagebundle_kk',
        'ui/table/messagebundle_en_GB',
        'ui/table/messagebundle_hr',
        'uxap/messagebundle_sk',
        'uxap/messagebundle_pl',
        'uxap/messagebundle_th',
        'uxap/messagebundle_fr',
        'uxap/messagebundle_en',
        'uxap/messagebundle_fi',
        'uxap/messagebundle_ro',
        'uxap/messagebundle_ja',
        'uxap/messagebundle_en_US',
        'uxap/messagebundle_ca',
        'uxap/messagebundle_uk',
        'uxap/messagebundle_no',
        'uxap/messagebundle_de',
        'uxap/messagebundle_bg',
        'uxap/messagebundle_ko',
        'uxap/messagebundle_el',
        'uxap/messagebundle_ms',
        'uxap/messagebundle_vi',
        'uxap/messagebundle_sl',
        'uxap/messagebundle_iw',
        'uxap/messagebundle_zh_TW',
        'uxap/messagebundle_hu',
        'uxap/messagebundle_cs',
        'uxap/messagebundle_tr',
        'uxap/messagebundle_it',
        'uxap/messagebundle_en_US_sappsd',
        'uxap/messagebundle_zh_CN',
        'uxap/messagebundle_lt',
        'uxap/messagebundle_en_US_saptrc',
        'uxap/messagebundle_ru',
        'uxap/messagebundle_es_MX',
        'uxap/messagebundle_nl',
        'uxap/messagebundle_et',
        'uxap/messagebundle_es',
        'uxap/messagebundle_hi',
        'uxap/messagebundle_da',
        'uxap/messagebundle_pt',
        'uxap/messagebundle_sh',
        'uxap/messagebundle_lv',
        'uxap/messagebundle_ar',
        'uxap/messagebundle_sv',
        'uxap/messagebundle_kk',
        'uxap/messagebundle_en_GB',
        'uxap/messagebundle_hr',
        'tnt/messagebundle_sk',
        'tnt/messagebundle_pl',
        'tnt/messagebundle_th',
        'tnt/messagebundle_fr',
        'tnt/messagebundle_en',
        'tnt/messagebundle_fi',
        'tnt/messagebundle_ro',
        'tnt/messagebundle_ja',
        'tnt/messagebundle_ca',
        'tnt/messagebundle_uk',
        'tnt/messagebundle_no',
        'tnt/messagebundle_de',
        'tnt/messagebundle_bg',
        'tnt/messagebundle_ko',
        'tnt/messagebundle_el',
        'tnt/messagebundle_ms',
        'tnt/messagebundle_vi',
        'tnt/messagebundle_sl',
        'tnt/messagebundle_iw',
        'tnt/messagebundle_zh_TW',
        'tnt/messagebundle_hu',
        'tnt/messagebundle_cs',
        'tnt/messagebundle_tr',
        'tnt/messagebundle_it',
        'tnt/messagebundle_en_US_sappsd',
        'tnt/messagebundle_zh_CN',
        'tnt/messagebundle_lt',
        'tnt/messagebundle_en_US_saptrc',
        'tnt/messagebundle_ru',
        'tnt/messagebundle_nl',
        'tnt/messagebundle_et',
        'tnt/messagebundle_es',
        'tnt/messagebundle_hi',
        'tnt/messagebundle_da',
        'tnt/messagebundle_pt',
        'tnt/messagebundle_sh',
        'tnt/messagebundle_lv',
        'tnt/messagebundle_ar',
        'tnt/messagebundle_sv',
        'tnt/messagebundle_kk',
        'tnt/messagebundle_hr',
        'f/messagebundle_sk',
        'f/messagebundle_pl',
        'f/messagebundle_th',
        'f/messagebundle_fr',
        'f/messagebundle_en',
        'f/messagebundle_fi',
        'f/messagebundle_ro',
        'f/messagebundle_ja',
        'f/messagebundle_ca',
        'f/messagebundle_uk',
        'f/messagebundle_no',
        'f/messagebundle_de',
        'f/messagebundle_bg',
        'f/messagebundle_ko',
        'f/messagebundle_el',
        'f/messagebundle_ms',
        'f/messagebundle_vi',
        'f/messagebundle_sl',
        'f/messagebundle_iw',
        'f/messagebundle_zh_TW',
        'f/messagebundle_hu',
        'f/messagebundle_cs',
        'f/messagebundle_tr',
        'f/messagebundle_it',
        'f/messagebundle_en_US_sappsd',
        'f/messagebundle_zh_CN',
        'f/messagebundle_lt',
        'f/messagebundle_en_US_saptrc',
        'f/messagebundle_ru',
        'f/messagebundle_es_MX',
        'f/messagebundle_nl',
        'f/messagebundle_et',
        'f/messagebundle_es',
        'f/messagebundle_hi',
        'f/messagebundle_da',
        'f/designtime/messagebundle_sk',
        'f/designtime/messagebundle_pl',
        'f/designtime/messagebundle_th',
        'f/designtime/messagebundle_fr',
        'f/designtime/messagebundle_en',
        'f/designtime/messagebundle_fi',
        'f/designtime/messagebundle_ro',
        'f/designtime/messagebundle_ja',
        'f/designtime/messagebundle_ca',
        'f/designtime/messagebundle_uk',
        'f/designtime/messagebundle_no',
        'f/designtime/messagebundle_de',
        'f/designtime/messagebundle_bg',
        'f/designtime/messagebundle_ko',
        'f/designtime/messagebundle_el',
        'f/designtime/messagebundle_ms',
        'f/designtime/messagebundle_vi',
        'f/designtime/messagebundle_sl',
        'f/designtime/messagebundle_iw',
        'f/designtime/messagebundle_zh_TW',
        'f/designtime/messagebundle_hu',
        'f/designtime/messagebundle_cs',
        'f/designtime/messagebundle_tr',
        'f/designtime/messagebundle_it',
        'f/designtime/messagebundle_en_US_sappsd',
        'f/designtime/messagebundle_zh_CN',
        'f/designtime/messagebundle_lt',
        'f/designtime/messagebundle_en_US_saptrc',
        'f/designtime/messagebundle_ru',
        'f/designtime/messagebundle_es_MX',
        'f/designtime/messagebundle_nl',
        'f/designtime/messagebundle_et',
        'f/designtime/messagebundle_es',
        'f/designtime/messagebundle_hi',
        'f/designtime/messagebundle_da',
        'f/designtime/messagebundle_pt',
        'f/designtime/messagebundle_sh',
        'f/designtime/messagebundle_lv',
        'f/designtime/messagebundle_ar',
        'f/designtime/messagebundle_sv',
        'f/designtime/messagebundle_kk',
        'f/designtime/messagebundle_en_GB',
        'f/designtime/messagebundle_hr',
        'f/messagebundle_pt',
        'f/messagebundle_sh',
        'f/messagebundle_lv',
        'f/messagebundle_ar',
        'f/messagebundle_sv',
        'f/messagebundle_kk',
        'f/messagebundle_en_GB',
        'f/messagebundle_hr',
        'm/messagebundle_sk',
        'm/messagebundle_pl',
        'm/messagebundle_th',
        'm/messagebundle_fr',
        'm/messagebundle_en',
        'm/messagebundle_fi',
        'm/messagebundle_ro',
        'm/messagebundle_ja',
        'm/messagebundle_ca',
        'm/messagebundle_uk',
        'm/messagebundle_no',
        'm/messagebundle_de',
        'm/messagebundle_bg',
        'm/messagebundle_ko',
        'm/messagebundle_el',
        'm/messagebundle_ms',
        'm/messagebundle_vi',
        'm/messagebundle_sl',
        'm/messagebundle_iw',
        'm/messagebundle_zh_TW',
        'm/messagebundle_hu',
        'm/messagebundle_cs',
        'm/messagebundle_tr',
        'm/messagebundle_it',
        'm/messagebundle_en_US_sappsd',
        'm/messagebundle_zh_CN',
        'm/messagebundle_lt',
        'm/messagebundle_en_US_saptrc',
        'm/messagebundle_ru',
        'm/messagebundle_nl',
        'm/messagebundle_et',
        'm/messagebundle_es',
        'm/messagebundle_hi',
        'm/messagebundle_da',
        'm/designtime/messagebundle_sk',
        'm/designtime/messagebundle_pl',
        'm/designtime/messagebundle_th',
        'm/designtime/messagebundle_fr',
        'm/designtime/messagebundle_en',
        'm/designtime/messagebundle_fi',
        'm/designtime/messagebundle_ro',
        'm/designtime/messagebundle_ja',
        'm/designtime/messagebundle_ca',
        'm/designtime/messagebundle_uk',
        'm/designtime/messagebundle_no',
        'm/designtime/messagebundle_de',
        'm/designtime/messagebundle_bg',
        'm/designtime/messagebundle_ko',
        'm/designtime/messagebundle_el',
        'm/designtime/messagebundle_ms',
        'm/designtime/messagebundle_vi',
        'm/designtime/messagebundle_sl',
        'm/designtime/messagebundle_iw',
        'm/designtime/messagebundle_zh_TW',
        'm/designtime/messagebundle_hu',
        'm/designtime/messagebundle_cs',
        'm/designtime/messagebundle_tr',
        'm/designtime/messagebundle_it',
        'm/designtime/messagebundle_en_US_sappsd',
        'm/designtime/messagebundle_zh_CN',
        'm/designtime/messagebundle_lt',
        'm/designtime/messagebundle_en_US_saptrc',
        'm/designtime/messagebundle_ru',
        'm/designtime/messagebundle_es_MX',
        'm/designtime/messagebundle_nl',
        'm/designtime/messagebundle_et',
        'm/designtime/messagebundle_es',
        'm/designtime/messagebundle_hi',
        'm/designtime/messagebundle_da',
        'm/designtime/messagebundle_pt',
        'm/designtime/messagebundle_sh',
        'm/designtime/messagebundle_lv',
        'm/designtime/messagebundle_ar',
        'm/designtime/messagebundle_sv',
        'm/designtime/messagebundle_kk',
        'm/designtime/messagebundle_en_GB',
        'm/designtime/messagebundle_hr',
        'm/messagebundle_pt',
        'm/messagebundle_sh',
        'm/messagebundle_lv',
        'm/messagebundle_ar',
        'm/messagebundle_sv',
        'm/messagebundle_kk',
        'm/messagebundle_en_GB',
        'm/messagebundle_hr',
    ],
    '1.108': [
        'ui/core/messagebundle',
        'ui/core/designtime/messagebundle',
        'ui/rta/messagebundle',
        'ui/integration/messagebundle',
        'ui/layout/messagebundle',
        'ui/layout/designtime/messagebundle',
        'ui/fl/messagebundle',
        'ui/fl/designtime/messagebundle',
        'ui/unified/messagebundle',
        'ui/unified/designtime/messagebundle',
        'ui/table/messagebundle',
        'ui/table/designtime/messagebundle',
        'uxap/messagebundle',
        'tnt/messagebundle',
        'f/messagebundle',
        'f/designtime/messagebundle',
        'm/messagebundle',
        'm/designtime/messagebundle',
        'ui/core/messagebundle_sk',
        'ui/core/messagebundle_pl',
        'ui/core/messagebundle_th',
        'ui/core/messagebundle_fr',
        'ui/core/messagebundle_en',
        'ui/core/messagebundle_fi',
        'ui/core/messagebundle_ro',
        'ui/core/messagebundle_ja',
        'ui/core/messagebundle_ca',
        'ui/core/messagebundle_pt_PT',
        'ui/core/messagebundle_uk',
        'ui/core/messagebundle_no',
        'ui/core/messagebundle_de',
        'ui/core/messagebundle_bg',
        'ui/core/messagebundle_ko',
        'ui/core/messagebundle_el',
        'ui/core/messagebundle_ms',
        'ui/core/messagebundle_id',
        'ui/core/messagebundle_vi',
        'ui/core/messagebundle_sl',
        'ui/core/messagebundle_iw',
        'ui/core/messagebundle_zh_TW',
        'ui/core/messagebundle_sr',
        'ui/core/messagebundle_en_US_saprigi',
        'ui/core/messagebundle_hu',
        'ui/core/messagebundle_cs',
        'ui/core/messagebundle_fr_CA',
        'ui/core/messagebundle_tr',
        'ui/core/messagebundle_it',
        'ui/core/messagebundle_en_US_sappsd',
        'ui/core/messagebundle_zh_CN',
        'ui/core/messagebundle_lt',
        'ui/core/messagebundle_en_US_saptrc',
        'ui/core/messagebundle_ru',
        'ui/core/messagebundle_es_MX',
        'ui/core/messagebundle_nl',
        'ui/core/messagebundle_et',
        'ui/core/messagebundle_mk',
        'ui/core/messagebundle_es',
        'ui/core/messagebundle_hi',
        'ui/core/messagebundle_da',
        'ui/core/designtime/messagebundle_en_US_saprigi',
        'ui/core/messagebundle_pt',
        'ui/core/messagebundle_cy',
        'ui/core/messagebundle_sh',
        'ui/core/messagebundle_lv',
        'ui/core/messagebundle_ar',
        'ui/core/messagebundle_sv',
        'ui/core/messagebundle_kk',
        'ui/core/messagebundle_en_GB',
        'ui/core/messagebundle_hr',
        'ui/rta/messagebundle_sk',
        'ui/rta/messagebundle_pl',
        'ui/rta/messagebundle_th',
        'ui/rta/messagebundle_fr',
        'ui/rta/messagebundle_en',
        'ui/rta/messagebundle_fi',
        'ui/rta/messagebundle_ro',
        'ui/rta/messagebundle_ja',
        'ui/rta/messagebundle_ca',
        'ui/rta/messagebundle_pt_PT',
        'ui/rta/messagebundle_uk',
        'ui/rta/messagebundle_no',
        'ui/rta/messagebundle_de',
        'ui/rta/messagebundle_bg',
        'ui/rta/messagebundle_ko',
        'ui/rta/messagebundle_el',
        'ui/rta/messagebundle_ms',
        'ui/rta/messagebundle_id',
        'ui/rta/messagebundle_vi',
        'ui/rta/messagebundle_sl',
        'ui/rta/messagebundle_iw',
        'ui/rta/messagebundle_zh_TW',
        'ui/rta/messagebundle_sr',
        'ui/rta/messagebundle_en_US_saprigi',
        'ui/rta/messagebundle_hu',
        'ui/rta/messagebundle_cs',
        'ui/rta/messagebundle_fr_CA',
        'ui/rta/messagebundle_tr',
        'ui/rta/messagebundle_it',
        'ui/rta/messagebundle_en_US_sappsd',
        'ui/rta/messagebundle_zh_CN',
        'ui/rta/messagebundle_lt',
        'ui/rta/messagebundle_en_US_saptrc',
        'ui/rta/messagebundle_ru',
        'ui/rta/messagebundle_es_MX',
        'ui/rta/messagebundle_nl',
        'ui/rta/messagebundle_et',
        'ui/rta/messagebundle_mk',
        'ui/rta/messagebundle_es',
        'ui/rta/messagebundle_hi',
        'ui/rta/messagebundle_da',
        'ui/rta/messagebundle_pt',
        'ui/rta/messagebundle_cy',
        'ui/rta/messagebundle_sh',
        'ui/rta/messagebundle_lv',
        'ui/rta/messagebundle_ar',
        'ui/rta/messagebundle_sv',
        'ui/rta/messagebundle_kk',
        'ui/rta/messagebundle_en_GB',
        'ui/rta/messagebundle_hr',
        'ui/integration/messagebundle_sk',
        'ui/integration/messagebundle_pl',
        'ui/integration/messagebundle_th',
        'ui/integration/messagebundle_fr',
        'ui/integration/messagebundle_en',
        'ui/integration/messagebundle_fi',
        'ui/integration/messagebundle_ro',
        'ui/integration/messagebundle_ja',
        'ui/integration/messagebundle_ca',
        'ui/integration/messagebundle_pt_PT',
        'ui/integration/messagebundle_uk',
        'ui/integration/messagebundle_no',
        'ui/integration/messagebundle_de',
        'ui/integration/messagebundle_bg',
        'ui/integration/messagebundle_ko',
        'ui/integration/messagebundle_el',
        'ui/integration/messagebundle_ms',
        'ui/integration/messagebundle_id',
        'ui/integration/messagebundle_vi',
        'ui/integration/messagebundle_sl',
        'ui/integration/messagebundle_iw',
        'ui/integration/messagebundle_zh_TW',
        'ui/integration/messagebundle_sr',
        'ui/integration/messagebundle_en_US_saprigi',
        'ui/integration/messagebundle_hu',
        'ui/integration/messagebundle_cs',
        'ui/integration/messagebundle_fr_CA',
        'ui/integration/messagebundle_tr',
        'ui/integration/messagebundle_it',
        'ui/integration/messagebundle_en_US_sappsd',
        'ui/integration/messagebundle_zh_CN',
        'ui/integration/messagebundle_lt',
        'ui/integration/messagebundle_en_US_saptrc',
        'ui/integration/messagebundle_ru',
        'ui/integration/messagebundle_es_MX',
        'ui/integration/messagebundle_nl',
        'ui/integration/messagebundle_et',
        'ui/integration/messagebundle_mk',
        'ui/integration/messagebundle_es',
        'ui/integration/messagebundle_hi',
        'ui/integration/messagebundle_da',
        'ui/integration/messagebundle_pt',
        'ui/integration/messagebundle_cy',
        'ui/integration/messagebundle_sh',
        'ui/integration/messagebundle_lv',
        'ui/integration/messagebundle_ar',
        'ui/integration/messagebundle_sv',
        'ui/integration/messagebundle_kk',
        'ui/integration/messagebundle_en_GB',
        'ui/integration/messagebundle_hr',
        'ui/layout/messagebundle_sk',
        'ui/layout/messagebundle_pl',
        'ui/layout/messagebundle_th',
        'ui/layout/messagebundle_fr',
        'ui/layout/messagebundle_en',
        'ui/layout/messagebundle_fi',
        'ui/layout/messagebundle_ro',
        'ui/layout/messagebundle_ja',
        'ui/layout/messagebundle_ca',
        'ui/layout/messagebundle_pt_PT',
        'ui/layout/messagebundle_uk',
        'ui/layout/messagebundle_no',
        'ui/layout/messagebundle_de',
        'ui/layout/messagebundle_bg',
        'ui/layout/messagebundle_ko',
        'ui/layout/messagebundle_el',
        'ui/layout/messagebundle_ms',
        'ui/layout/messagebundle_id',
        'ui/layout/messagebundle_vi',
        'ui/layout/messagebundle_sl',
        'ui/layout/messagebundle_iw',
        'ui/layout/messagebundle_zh_TW',
        'ui/layout/messagebundle_sr',
        'ui/layout/messagebundle_en_US_saprigi',
        'ui/layout/messagebundle_hu',
        'ui/layout/messagebundle_cs',
        'ui/layout/messagebundle_fr_CA',
        'ui/layout/messagebundle_tr',
        'ui/layout/messagebundle_it',
        'ui/layout/messagebundle_en_US_sappsd',
        'ui/layout/messagebundle_zh_CN',
        'ui/layout/messagebundle_lt',
        'ui/layout/messagebundle_en_US_saptrc',
        'ui/layout/messagebundle_ru',
        'ui/layout/messagebundle_es_MX',
        'ui/layout/messagebundle_nl',
        'ui/layout/messagebundle_et',
        'ui/layout/messagebundle_mk',
        'ui/layout/messagebundle_es',
        'ui/layout/messagebundle_hi',
        'ui/layout/messagebundle_da',
        'ui/layout/designtime/messagebundle_sk',
        'ui/layout/designtime/messagebundle_pl',
        'ui/layout/designtime/messagebundle_th',
        'ui/layout/designtime/messagebundle_fr',
        'ui/layout/designtime/messagebundle_en',
        'ui/layout/designtime/messagebundle_fi',
        'ui/layout/designtime/messagebundle_ro',
        'ui/layout/designtime/messagebundle_ja',
        'ui/layout/designtime/messagebundle_ca',
        'ui/layout/designtime/messagebundle_pt_PT',
        'ui/layout/designtime/messagebundle_uk',
        'ui/layout/designtime/messagebundle_no',
        'ui/layout/designtime/messagebundle_de',
        'ui/layout/designtime/messagebundle_bg',
        'ui/layout/designtime/messagebundle_ko',
        'ui/layout/designtime/messagebundle_el',
        'ui/layout/designtime/messagebundle_ms',
        'ui/layout/designtime/messagebundle_id',
        'ui/layout/designtime/messagebundle_vi',
        'ui/layout/designtime/messagebundle_sl',
        'ui/layout/designtime/messagebundle_iw',
        'ui/layout/designtime/messagebundle_zh_TW',
        'ui/layout/designtime/messagebundle_sr',
        'ui/layout/designtime/messagebundle_en_US_saprigi',
        'ui/layout/designtime/messagebundle_hu',
        'ui/layout/designtime/messagebundle_cs',
        'ui/layout/designtime/messagebundle_fr_CA',
        'ui/layout/designtime/messagebundle_tr',
        'ui/layout/designtime/messagebundle_it',
        'ui/layout/designtime/messagebundle_en_US_sappsd',
        'ui/layout/designtime/messagebundle_zh_CN',
        'ui/layout/designtime/messagebundle_lt',
        'ui/layout/designtime/messagebundle_en_US_saptrc',
        'ui/layout/designtime/messagebundle_ru',
        'ui/layout/designtime/messagebundle_es_MX',
        'ui/layout/designtime/messagebundle_nl',
        'ui/layout/designtime/messagebundle_et',
        'ui/layout/designtime/messagebundle_mk',
        'ui/layout/designtime/messagebundle_es',
        'ui/layout/designtime/messagebundle_hi',
        'ui/layout/designtime/messagebundle_da',
        'ui/layout/designtime/messagebundle_pt',
        'ui/layout/designtime/messagebundle_cy',
        'ui/layout/designtime/messagebundle_sh',
        'ui/layout/designtime/messagebundle_lv',
        'ui/layout/designtime/messagebundle_ar',
        'ui/layout/designtime/messagebundle_sv',
        'ui/layout/designtime/messagebundle_kk',
        'ui/layout/designtime/messagebundle_en_GB',
        'ui/layout/designtime/messagebundle_hr',
        'ui/layout/messagebundle_pt',
        'ui/layout/messagebundle_cy',
        'ui/layout/messagebundle_sh',
        'ui/layout/messagebundle_lv',
        'ui/layout/messagebundle_ar',
        'ui/layout/messagebundle_sv',
        'ui/layout/messagebundle_kk',
        'ui/layout/messagebundle_en_GB',
        'ui/layout/messagebundle_hr',
        'ui/fl/messagebundle_sk',
        'ui/fl/messagebundle_pl',
        'ui/fl/messagebundle_th',
        'ui/fl/messagebundle_fr',
        'ui/fl/messagebundle_en',
        'ui/fl/messagebundle_fi',
        'ui/fl/messagebundle_ro',
        'ui/fl/messagebundle_ja',
        'ui/fl/messagebundle_ca',
        'ui/fl/messagebundle_pt_PT',
        'ui/fl/messagebundle_uk',
        'ui/fl/messagebundle_no',
        'ui/fl/messagebundle_de',
        'ui/fl/messagebundle_bg',
        'ui/fl/messagebundle_ko',
        'ui/fl/messagebundle_el',
        'ui/fl/messagebundle_ms',
        'ui/fl/messagebundle_id',
        'ui/fl/messagebundle_vi',
        'ui/fl/messagebundle_sl',
        'ui/fl/messagebundle_iw',
        'ui/fl/messagebundle_zh_TW',
        'ui/fl/messagebundle_sr',
        'ui/fl/messagebundle_en_US_saprigi',
        'ui/fl/messagebundle_hu',
        'ui/fl/messagebundle_cs',
        'ui/fl/messagebundle_fr_CA',
        'ui/fl/messagebundle_tr',
        'ui/fl/messagebundle_it',
        'ui/fl/messagebundle_en_US_sappsd',
        'ui/fl/messagebundle_zh_CN',
        'ui/fl/messagebundle_lt',
        'ui/fl/messagebundle_en_US_saptrc',
        'ui/fl/messagebundle_ru',
        'ui/fl/messagebundle_es_MX',
        'ui/fl/messagebundle_nl',
        'ui/fl/messagebundle_et',
        'ui/fl/messagebundle_mk',
        'ui/fl/messagebundle_es',
        'ui/fl/messagebundle_hi',
        'ui/fl/messagebundle_da',
        'ui/fl/designtime/messagebundle_sk',
        'ui/fl/designtime/messagebundle_pl',
        'ui/fl/designtime/messagebundle_th',
        'ui/fl/designtime/messagebundle_fr',
        'ui/fl/designtime/messagebundle_en',
        'ui/fl/designtime/messagebundle_fi',
        'ui/fl/designtime/messagebundle_ro',
        'ui/fl/designtime/messagebundle_ja',
        'ui/fl/designtime/messagebundle_ca',
        'ui/fl/designtime/messagebundle_pt_PT',
        'ui/fl/designtime/messagebundle_uk',
        'ui/fl/designtime/messagebundle_no',
        'ui/fl/designtime/messagebundle_de',
        'ui/fl/designtime/messagebundle_bg',
        'ui/fl/designtime/messagebundle_ko',
        'ui/fl/designtime/messagebundle_el',
        'ui/fl/designtime/messagebundle_ms',
        'ui/fl/designtime/messagebundle_id',
        'ui/fl/designtime/messagebundle_vi',
        'ui/fl/designtime/messagebundle_sl',
        'ui/fl/designtime/messagebundle_iw',
        'ui/fl/designtime/messagebundle_zh_TW',
        'ui/fl/designtime/messagebundle_sr',
        'ui/fl/designtime/messagebundle_en_US_saprigi',
        'ui/fl/designtime/messagebundle_hu',
        'ui/fl/designtime/messagebundle_cs',
        'ui/fl/designtime/messagebundle_fr_CA',
        'ui/fl/designtime/messagebundle_tr',
        'ui/fl/designtime/messagebundle_it',
        'ui/fl/designtime/messagebundle_en_US_sappsd',
        'ui/fl/designtime/messagebundle_zh_CN',
        'ui/fl/designtime/messagebundle_lt',
        'ui/fl/designtime/messagebundle_en_US_saptrc',
        'ui/fl/designtime/messagebundle_ru',
        'ui/fl/designtime/messagebundle_es_MX',
        'ui/fl/designtime/messagebundle_nl',
        'ui/fl/designtime/messagebundle_et',
        'ui/fl/designtime/messagebundle_mk',
        'ui/fl/designtime/messagebundle_es',
        'ui/fl/designtime/messagebundle_hi',
        'ui/fl/designtime/messagebundle_da',
        'ui/fl/designtime/messagebundle_pt',
        'ui/fl/designtime/messagebundle_cy',
        'ui/fl/designtime/messagebundle_sh',
        'ui/fl/designtime/messagebundle_lv',
        'ui/fl/designtime/messagebundle_ar',
        'ui/fl/designtime/messagebundle_sv',
        'ui/fl/designtime/messagebundle_kk',
        'ui/fl/designtime/messagebundle_en_GB',
        'ui/fl/designtime/messagebundle_hr',
        'ui/fl/messagebundle_pt',
        'ui/fl/messagebundle_cy',
        'ui/fl/messagebundle_sh',
        'ui/fl/messagebundle_lv',
        'ui/fl/messagebundle_ar',
        'ui/fl/messagebundle_sv',
        'ui/fl/messagebundle_kk',
        'ui/fl/messagebundle_en_GB',
        'ui/fl/messagebundle_hr',
        'ui/unified/messagebundle_sk',
        'ui/unified/messagebundle_pl',
        'ui/unified/messagebundle_th',
        'ui/unified/messagebundle_fr',
        'ui/unified/messagebundle_en',
        'ui/unified/messagebundle_fi',
        'ui/unified/messagebundle_ro',
        'ui/unified/messagebundle_ja',
        'ui/unified/messagebundle_ca',
        'ui/unified/messagebundle_pt_PT',
        'ui/unified/messagebundle_uk',
        'ui/unified/messagebundle_no',
        'ui/unified/messagebundle_de',
        'ui/unified/messagebundle_bg',
        'ui/unified/messagebundle_ko',
        'ui/unified/messagebundle_el',
        'ui/unified/messagebundle_ms',
        'ui/unified/messagebundle_id',
        'ui/unified/messagebundle_vi',
        'ui/unified/messagebundle_sl',
        'ui/unified/messagebundle_iw',
        'ui/unified/messagebundle_zh_TW',
        'ui/unified/messagebundle_sr',
        'ui/unified/messagebundle_en_US_saprigi',
        'ui/unified/messagebundle_hu',
        'ui/unified/messagebundle_cs',
        'ui/unified/messagebundle_fr_CA',
        'ui/unified/messagebundle_tr',
        'ui/unified/messagebundle_it',
        'ui/unified/messagebundle_en_US_sappsd',
        'ui/unified/messagebundle_zh_CN',
        'ui/unified/messagebundle_lt',
        'ui/unified/messagebundle_en_US_saptrc',
        'ui/unified/messagebundle_ru',
        'ui/unified/messagebundle_es_MX',
        'ui/unified/messagebundle_nl',
        'ui/unified/messagebundle_et',
        'ui/unified/messagebundle_mk',
        'ui/unified/messagebundle_es',
        'ui/unified/messagebundle_hi',
        'ui/unified/messagebundle_da',
        'ui/unified/designtime/messagebundle_sk',
        'ui/unified/designtime/messagebundle_pl',
        'ui/unified/designtime/messagebundle_th',
        'ui/unified/designtime/messagebundle_fr',
        'ui/unified/designtime/messagebundle_en',
        'ui/unified/designtime/messagebundle_fi',
        'ui/unified/designtime/messagebundle_ro',
        'ui/unified/designtime/messagebundle_ja',
        'ui/unified/designtime/messagebundle_ca',
        'ui/unified/designtime/messagebundle_pt_PT',
        'ui/unified/designtime/messagebundle_uk',
        'ui/unified/designtime/messagebundle_no',
        'ui/unified/designtime/messagebundle_de',
        'ui/unified/designtime/messagebundle_bg',
        'ui/unified/designtime/messagebundle_ko',
        'ui/unified/designtime/messagebundle_el',
        'ui/unified/designtime/messagebundle_ms',
        'ui/unified/designtime/messagebundle_id',
        'ui/unified/designtime/messagebundle_vi',
        'ui/unified/designtime/messagebundle_sl',
        'ui/unified/designtime/messagebundle_iw',
        'ui/unified/designtime/messagebundle_zh_TW',
        'ui/unified/designtime/messagebundle_sr',
        'ui/unified/designtime/messagebundle_en_US_saprigi',
        'ui/unified/designtime/messagebundle_hu',
        'ui/unified/designtime/messagebundle_cs',
        'ui/unified/designtime/messagebundle_fr_CA',
        'ui/unified/designtime/messagebundle_tr',
        'ui/unified/designtime/messagebundle_it',
        'ui/unified/designtime/messagebundle_en_US_sappsd',
        'ui/unified/designtime/messagebundle_zh_CN',
        'ui/unified/designtime/messagebundle_lt',
        'ui/unified/designtime/messagebundle_en_US_saptrc',
        'ui/unified/designtime/messagebundle_ru',
        'ui/unified/designtime/messagebundle_es_MX',
        'ui/unified/designtime/messagebundle_nl',
        'ui/unified/designtime/messagebundle_et',
        'ui/unified/designtime/messagebundle_mk',
        'ui/unified/designtime/messagebundle_es',
        'ui/unified/designtime/messagebundle_hi',
        'ui/unified/designtime/messagebundle_da',
        'ui/unified/designtime/messagebundle_pt',
        'ui/unified/designtime/messagebundle_cy',
        'ui/unified/designtime/messagebundle_sh',
        'ui/unified/designtime/messagebundle_lv',
        'ui/unified/designtime/messagebundle_ar',
        'ui/unified/designtime/messagebundle_sv',
        'ui/unified/designtime/messagebundle_kk',
        'ui/unified/designtime/messagebundle_en_GB',
        'ui/unified/designtime/messagebundle_hr',
        'ui/unified/messagebundle_pt',
        'ui/unified/messagebundle_cy',
        'ui/unified/messagebundle_sh',
        'ui/unified/messagebundle_lv',
        'ui/unified/messagebundle_ar',
        'ui/unified/messagebundle_sv',
        'ui/unified/messagebundle_kk',
        'ui/unified/messagebundle_en_GB',
        'ui/unified/messagebundle_hr',
        'ui/table/messagebundle_sk',
        'ui/table/messagebundle_pl',
        'ui/table/messagebundle_th',
        'ui/table/messagebundle_fr',
        'ui/table/messagebundle_en',
        'ui/table/messagebundle_fi',
        'ui/table/messagebundle_ro',
        'ui/table/messagebundle_ja',
        'ui/table/messagebundle_ca',
        'ui/table/messagebundle_pt_PT',
        'ui/table/messagebundle_uk',
        'ui/table/messagebundle_no',
        'ui/table/messagebundle_de',
        'ui/table/messagebundle_bg',
        'ui/table/messagebundle_ko',
        'ui/table/messagebundle_el',
        'ui/table/messagebundle_ms',
        'ui/table/messagebundle_id',
        'ui/table/messagebundle_vi',
        'ui/table/messagebundle_sl',
        'ui/table/messagebundle_iw',
        'ui/table/messagebundle_zh_TW',
        'ui/table/messagebundle_sr',
        'ui/table/messagebundle_en_US_saprigi',
        'ui/table/messagebundle_hu',
        'ui/table/messagebundle_cs',
        'ui/table/messagebundle_fr_CA',
        'ui/table/messagebundle_tr',
        'ui/table/messagebundle_it',
        'ui/table/messagebundle_en_US_sappsd',
        'ui/table/messagebundle_zh_CN',
        'ui/table/messagebundle_lt',
        'ui/table/messagebundle_en_US_saptrc',
        'ui/table/messagebundle_ru',
        'ui/table/messagebundle_es_MX',
        'ui/table/messagebundle_nl',
        'ui/table/messagebundle_et',
        'ui/table/messagebundle_mk',
        'ui/table/messagebundle_es',
        'ui/table/messagebundle_hi',
        'ui/table/messagebundle_da',
        'ui/table/designtime/messagebundle_en_US_saprigi',
        'ui/table/messagebundle_pt',
        'ui/table/messagebundle_cy',
        'ui/table/messagebundle_sh',
        'ui/table/messagebundle_lv',
        'ui/table/messagebundle_ar',
        'ui/table/messagebundle_sv',
        'ui/table/messagebundle_kk',
        'ui/table/messagebundle_en_GB',
        'ui/table/messagebundle_hr',
        'uxap/messagebundle_sk',
        'uxap/messagebundle_pl',
        'uxap/messagebundle_th',
        'uxap/messagebundle_fr',
        'uxap/messagebundle_en',
        'uxap/messagebundle_fi',
        'uxap/messagebundle_ro',
        'uxap/messagebundle_ja',
        'uxap/messagebundle_ca',
        'uxap/messagebundle_pt_PT',
        'uxap/messagebundle_uk',
        'uxap/messagebundle_no',
        'uxap/messagebundle_de',
        'uxap/messagebundle_bg',
        'uxap/messagebundle_ko',
        'uxap/messagebundle_el',
        'uxap/messagebundle_ms',
        'uxap/messagebundle_id',
        'uxap/messagebundle_vi',
        'uxap/messagebundle_sl',
        'uxap/messagebundle_iw',
        'uxap/messagebundle_zh_TW',
        'uxap/messagebundle_sr',
        'uxap/messagebundle_en_US_saprigi',
        'uxap/messagebundle_hu',
        'uxap/messagebundle_cs',
        'uxap/messagebundle_fr_CA',
        'uxap/messagebundle_tr',
        'uxap/messagebundle_it',
        'uxap/messagebundle_en_US_sappsd',
        'uxap/messagebundle_zh_CN',
        'uxap/messagebundle_lt',
        'uxap/messagebundle_en_US_saptrc',
        'uxap/messagebundle_ru',
        'uxap/messagebundle_es_MX',
        'uxap/messagebundle_nl',
        'uxap/messagebundle_et',
        'uxap/messagebundle_mk',
        'uxap/messagebundle_es',
        'uxap/messagebundle_hi',
        'uxap/messagebundle_da',
        'uxap/messagebundle_pt',
        'uxap/messagebundle_cy',
        'uxap/messagebundle_sh',
        'uxap/messagebundle_lv',
        'uxap/messagebundle_ar',
        'uxap/messagebundle_sv',
        'uxap/messagebundle_kk',
        'uxap/messagebundle_en_GB',
        'uxap/messagebundle_hr',
        'tnt/messagebundle_sk',
        'tnt/messagebundle_pl',
        'tnt/messagebundle_th',
        'tnt/messagebundle_fr',
        'tnt/messagebundle_en',
        'tnt/messagebundle_fi',
        'tnt/messagebundle_ro',
        'tnt/messagebundle_ja',
        'tnt/messagebundle_ca',
        'tnt/messagebundle_pt_PT',
        'tnt/messagebundle_uk',
        'tnt/messagebundle_no',
        'tnt/messagebundle_de',
        'tnt/messagebundle_bg',
        'tnt/messagebundle_ko',
        'tnt/messagebundle_el',
        'tnt/messagebundle_ms',
        'tnt/messagebundle_id',
        'tnt/messagebundle_vi',
        'tnt/messagebundle_sl',
        'tnt/messagebundle_iw',
        'tnt/messagebundle_zh_TW',
        'tnt/messagebundle_sr',
        'tnt/messagebundle_en_US_saprigi',
        'tnt/messagebundle_hu',
        'tnt/messagebundle_cs',
        'tnt/messagebundle_fr_CA',
        'tnt/messagebundle_tr',
        'tnt/messagebundle_it',
        'tnt/messagebundle_en_US_sappsd',
        'tnt/messagebundle_zh_CN',
        'tnt/messagebundle_lt',
        'tnt/messagebundle_en_US_saptrc',
        'tnt/messagebundle_ru',
        'tnt/messagebundle_es_MX',
        'tnt/messagebundle_nl',
        'tnt/messagebundle_et',
        'tnt/messagebundle_mk',
        'tnt/messagebundle_es',
        'tnt/messagebundle_hi',
        'tnt/messagebundle_da',
        'tnt/messagebundle_pt',
        'tnt/messagebundle_cy',
        'tnt/messagebundle_sh',
        'tnt/messagebundle_lv',
        'tnt/messagebundle_ar',
        'tnt/messagebundle_sv',
        'tnt/messagebundle_kk',
        'tnt/messagebundle_en_GB',
        'tnt/messagebundle_hr',
        'f/messagebundle_sk',
        'f/messagebundle_pl',
        'f/messagebundle_th',
        'f/messagebundle_fr',
        'f/messagebundle_en',
        'f/messagebundle_fi',
        'f/messagebundle_ro',
        'f/messagebundle_ja',
        'f/messagebundle_ca',
        'f/messagebundle_pt_PT',
        'f/messagebundle_uk',
        'f/messagebundle_no',
        'f/messagebundle_de',
        'f/messagebundle_bg',
        'f/messagebundle_ko',
        'f/messagebundle_el',
        'f/messagebundle_ms',
        'f/messagebundle_id',
        'f/messagebundle_vi',
        'f/messagebundle_sl',
        'f/messagebundle_iw',
        'f/messagebundle_zh_TW',
        'f/messagebundle_sr',
        'f/messagebundle_en_US_saprigi',
        'f/messagebundle_hu',
        'f/messagebundle_cs',
        'f/messagebundle_fr_CA',
        'f/messagebundle_tr',
        'f/messagebundle_it',
        'f/messagebundle_en_US_sappsd',
        'f/messagebundle_zh_CN',
        'f/messagebundle_lt',
        'f/messagebundle_en_US_saptrc',
        'f/messagebundle_ru',
        'f/messagebundle_es_MX',
        'f/messagebundle_nl',
        'f/messagebundle_et',
        'f/messagebundle_mk',
        'f/messagebundle_es',
        'f/messagebundle_hi',
        'f/messagebundle_da',
        'f/designtime/messagebundle_sk',
        'f/designtime/messagebundle_pl',
        'f/designtime/messagebundle_th',
        'f/designtime/messagebundle_fr',
        'f/designtime/messagebundle_en',
        'f/designtime/messagebundle_fi',
        'f/designtime/messagebundle_ro',
        'f/designtime/messagebundle_ja',
        'f/designtime/messagebundle_ca',
        'f/designtime/messagebundle_pt_PT',
        'f/designtime/messagebundle_uk',
        'f/designtime/messagebundle_no',
        'f/designtime/messagebundle_de',
        'f/designtime/messagebundle_bg',
        'f/designtime/messagebundle_ko',
        'f/designtime/messagebundle_el',
        'f/designtime/messagebundle_ms',
        'f/designtime/messagebundle_id',
        'f/designtime/messagebundle_vi',
        'f/designtime/messagebundle_sl',
        'f/designtime/messagebundle_iw',
        'f/designtime/messagebundle_zh_TW',
        'f/designtime/messagebundle_sr',
        'f/designtime/messagebundle_en_US_saprigi',
        'f/designtime/messagebundle_hu',
        'f/designtime/messagebundle_cs',
        'f/designtime/messagebundle_fr_CA',
        'f/designtime/messagebundle_tr',
        'f/designtime/messagebundle_it',
        'f/designtime/messagebundle_en_US_sappsd',
        'f/designtime/messagebundle_zh_CN',
        'f/designtime/messagebundle_lt',
        'f/designtime/messagebundle_en_US_saptrc',
        'f/designtime/messagebundle_ru',
        'f/designtime/messagebundle_es_MX',
        'f/designtime/messagebundle_nl',
        'f/designtime/messagebundle_et',
        'f/designtime/messagebundle_mk',
        'f/designtime/messagebundle_es',
        'f/designtime/messagebundle_hi',
        'f/designtime/messagebundle_da',
        'f/designtime/messagebundle_pt',
        'f/designtime/messagebundle_cy',
        'f/designtime/messagebundle_sh',
        'f/designtime/messagebundle_lv',
        'f/designtime/messagebundle_ar',
        'f/designtime/messagebundle_sv',
        'f/designtime/messagebundle_kk',
        'f/designtime/messagebundle_en_GB',
        'f/designtime/messagebundle_hr',
        'f/messagebundle_pt',
        'f/messagebundle_cy',
        'f/messagebundle_sh',
        'f/messagebundle_lv',
        'f/messagebundle_ar',
        'f/messagebundle_sv',
        'f/messagebundle_kk',
        'f/messagebundle_en_GB',
        'f/messagebundle_hr',
        'm/messagebundle_sk',
        'm/messagebundle_pl',
        'm/messagebundle_th',
        'm/messagebundle_fr',
        'm/messagebundle_en',
        'm/messagebundle_fi',
        'm/messagebundle_ro',
        'm/messagebundle_ja',
        'm/messagebundle_ca',
        'm/messagebundle_pt_PT',
        'm/messagebundle_uk',
        'm/messagebundle_no',
        'm/messagebundle_de',
        'm/messagebundle_bg',
        'm/messagebundle_ko',
        'm/messagebundle_el',
        'm/messagebundle_ms',
        'm/messagebundle_id',
        'm/messagebundle_vi',
        'm/messagebundle_sl',
        'm/messagebundle_iw',
        'm/messagebundle_zh_TW',
        'm/messagebundle_sr',
        'm/messagebundle_en_US_saprigi',
        'm/messagebundle_hu',
        'm/messagebundle_cs',
        'm/messagebundle_fr_CA',
        'm/messagebundle_tr',
        'm/messagebundle_it',
        'm/messagebundle_en_US_sappsd',
        'm/messagebundle_zh_CN',
        'm/messagebundle_lt',
        'm/messagebundle_en_US_saptrc',
        'm/messagebundle_ru',
        'm/messagebundle_es_MX',
        'm/messagebundle_nl',
        'm/messagebundle_et',
        'm/messagebundle_mk',
        'm/messagebundle_es',
        'm/messagebundle_hi',
        'm/messagebundle_da',
        'm/designtime/messagebundle_sk',
        'm/designtime/messagebundle_pl',
        'm/designtime/messagebundle_th',
        'm/designtime/messagebundle_fr',
        'm/designtime/messagebundle_en',
        'm/designtime/messagebundle_fi',
        'm/designtime/messagebundle_ro',
        'm/designtime/messagebundle_ja',
        'm/designtime/messagebundle_ca',
        'm/designtime/messagebundle_pt_PT',
        'm/designtime/messagebundle_uk',
        'm/designtime/messagebundle_no',
        'm/designtime/messagebundle_de',
        'm/designtime/messagebundle_bg',
        'm/designtime/messagebundle_ko',
        'm/designtime/messagebundle_el',
        'm/designtime/messagebundle_ms',
        'm/designtime/messagebundle_id',
        'm/designtime/messagebundle_vi',
        'm/designtime/messagebundle_sl',
        'm/designtime/messagebundle_iw',
        'm/designtime/messagebundle_zh_TW',
        'm/designtime/messagebundle_sr',
        'm/designtime/messagebundle_en_US_saprigi',
        'm/designtime/messagebundle_hu',
        'm/designtime/messagebundle_cs',
        'm/designtime/messagebundle_fr_CA',
        'm/designtime/messagebundle_tr',
        'm/designtime/messagebundle_it',
        'm/designtime/messagebundle_en_US_sappsd',
        'm/designtime/messagebundle_zh_CN',
        'm/designtime/messagebundle_lt',
        'm/designtime/messagebundle_en_US_saptrc',
        'm/designtime/messagebundle_ru',
        'm/designtime/messagebundle_es_MX',
        'm/designtime/messagebundle_nl',
        'm/designtime/messagebundle_et',
        'm/designtime/messagebundle_mk',
        'm/designtime/messagebundle_es',
        'm/designtime/messagebundle_hi',
        'm/designtime/messagebundle_da',
        'm/designtime/messagebundle_pt',
        'm/designtime/messagebundle_cy',
        'm/designtime/messagebundle_sh',
        'm/designtime/messagebundle_lv',
        'm/designtime/messagebundle_ar',
        'm/designtime/messagebundle_sv',
        'm/designtime/messagebundle_kk',
        'm/designtime/messagebundle_en_GB',
        'm/designtime/messagebundle_hr',
        'm/messagebundle_pt',
        'm/messagebundle_cy',
        'm/messagebundle_sh',
        'm/messagebundle_lv',
        'm/messagebundle_ar',
        'm/messagebundle_sv',
        'm/messagebundle_kk',
        'm/messagebundle_en_GB',
        'm/messagebundle_hr',
    ],
}

const thirdpartyWebComponentsCldr = {
    '1.108': [
        'hu-8894ff20.js',
        'id-4e1f336f.js',
        'ar_EG-bec371f8.js',
        'ms-97288878.js',
        'ar-3d86671f.js',
        'it_CH-96f6448e.js',
        'es_UY-3145d111.js',
        'en_PG-90ae5ac9.js',
        'he-c7dd8770.js',
        'pt_PT-6f58c38d.js',
        'sr_Latn-66ea0243.js',
        'ar_SA-013516b9.js',
        'en_IE-31301e64.js',
        'sv-704380a3.js',
        'fr_BE-0a0b1e89.js',
        'es_VE-9855c07f.js',
        'es-2987b3bf.js',
        'it-2f7ca2cc.js',
        'da-b8216f78.js',
        'es_MX-ca227fd9.js',
        'et-c8b012d9.js',
        'bg-c8a3d631.js',
        'es_AR-c9568bef.js',
        'zh_SG-decc6172.js',
        'ro-cf279a8d.js',
        'de-db7ee200.js',
        'tr-a75c54c5.js',
        'en_ZA-a4a6c2af.js',
        'hi-02d890ff.js',
        'pl-e69ff58a.js',
        'fr-f90c8dbe.js',
        'en_NZ-1ac8fca7.js',
        'pt-b6593b86.js',
        'fr_CA-69115871.js',
        'uk-2ea9760e.js',
        'ca-432aede8.js',
        'de_CH-b2e7405d.js',
        'ko-580a2045.js',
        'nl_BE-ae42d671.js',
        'el-bc8ea43c.js',
        'en-852a3c47.js',
        'th-a3f0b98a.js',
        'es_PE-313ad09c.js',
        'fr_CH-67cec36a.js',
        'nl-624d50c1.js',
        'sr-d3b5a8a9.js',
        'zh_TW-22e4094b.js',
        'vi-0ee42fc7.js',
        'lt-ee0f5d04.js',
        'nb-d77ab65a.js',
        'en_SG-f783b9e0.js',
        'en_HK-8e388c7e.js',
        'fa-270906e4.js',
        'hr-ce839bd8.js',
        'de_AT-16212e69.js',
        'zh_HK-402bf471.js',
        'es_BO-f80d4cab.js',
        'es_CO-8ed671f5.js',
        'sl-0d949839.js',
        'en_AU-a22d2bd1.js',
        'cs-cb494530.js',
        'ru-a41bc6ce.js',
        'el_CY-32899bf5.js',
        'lv-b18d4611.js',
        'en_IN-a8cac790.js',
        'kk-4d418f87.js',
        'zh_CN-9347b38b.js',
        'ru_UA-60325a6e.js',
        'es_CL-e69a20cc.js',
        'en_GB-06fb3326.js',
        'ja-b852efec.js',
        'fr_LU-41d18384.js',
        'fi-5cb24937.js',
        'sk-a3e7e927.js',
    ]
}

// launchpad path is always like e.g. /launchpad/path-name
//      path is not like /launchpad/path-name[/something/here]
//      otherwise server throws a 404
function launchpadUrl() {
    return `${location.origin}${location.pathname}`;
}

async function isUrlInCache({ url, cacheName }) {
    if (typeof caches === 'undefined') return false;
    const cache = await caches.open(cacheName);
    return await cache.match(url)
}

async function addUrlToCache({ url, cacheName }) {
    if (typeof caches === 'undefined') return;

    try {
        const response = await fetch(url);
        if (response.ok) {
            const cache = await caches.open(cacheName);
            await cache.put(url, response);
            appCacheLog(`added to cache ${cacheName}`, url);
        }
    } catch (err) {
        appCacheError(`unable to addUrlToCache ${url}`);
    }
}

// If app is not offline, we can remove the launchpad main page from workbox cache
//  otherwise even after logout we will see the launchpad screen
function removeLaunchpadFromCache() {
    if (typeof caches === 'undefined') return;

    const url = `${location.origin}${location.pathname}`;
    if (!AppCache.isOffline) {
        let cacheName = '';
        if (new RegExp('/public/launchpad/').test(url)) cacheName = 'p9pwa-public';
        else if (new RegExp('/launchpad/').test(url)) cacheName = 'p9pwa-launchpad';

        if (cacheName.length > 0) {
            caches.open(cacheName).then(c => c.delete(url));
        }
    }
}

function determineCacheNameFromUrl(url) {
    if (new RegExp('/public/launchpad/').test(url)) return 'p9pwa-public';
    if (new RegExp('/launchpad/').test(url)) return 'p9pwa-launchpad';

    const publicRe = [
        new RegExp('/public/application/'),
        new RegExp('/public/neptune/'),
        new RegExp('/public/fontawesome/'),
        new RegExp('/public/highsuite/'),
        new RegExp('/public/css/')
    ];
    if (publicRe.some(re => re.test(url))) {
        return 'p9pwa-public';
    }

    if (new RegExp('https://openui5.hana.ondemand.com/').test(url)) return 'p9pwa-ui5-cdn';
    if (new RegExp('https://sapui5.hana.ondemand.com/').test(url)) return 'p9pwa-ui5-cdn';
    
    if (new RegExp('/public/openui5/').test(url)) return 'p9pwa-ui5';

    const mediaRe = [
        new RegExp('/public/images/'),
        new RegExp('/public/icons/'),
        new RegExp('/media/'),
        new RegExp('\.(png|jpg|jpeg|svg|gif|webp)$')
    ];
    if (mediaRe.some(re => re.test(url))) {
        return 'p9pwa-images';
    }

    if (new RegExp('/public/').test(url)) {
        return 'p9pwa-public';
    }

    // default
    return 'p9pwa-public';
}

// On first install PWA does not cache the launchpad
// since the install event occurs after the page has been loaded
// e.g. random login images or other requests which might be part 
const _pwaResources = {};
function setCachablePwaResources() {
    _pwaResources[launchpadUrl()] = { url: launchpadUrl(), cacheName: determineCacheNameFromUrl(launchpadUrl()) };

    const pwaJsonUrl = `${AppCache.Url}/public/launchpad/${AppCache.launchpadID}/pwa.json`;
    _pwaResources[pwaJsonUrl] = {
        cacheName: 'p9pwa-launchpad',
        url: pwaJsonUrl,
    };

    // commonly used libraries
    const sapVersion = sap.ui.version.split('.').slice(0, 2).join('.')
    const libs = [
        'jquery.sap.storage.js',
        'sap/m/MessageBox.js',
        'sap/m/MessageToast.js',
        'sap/ui/thirdparty/jqueryui/jquery-ui-core.js',
        'sap/ui/thirdparty/jqueryui/jquery-ui-sortable.js',
        'sap/ui/thirdparty/jqueryui/jquery-ui-widget.js',
        'sap/ui/core/format/DateFormat.js',
        'sap/ui/core/format/NumberFormat.js',
        'sap/ui/core/format/FileSizeFormat.js',
    ];
    for (const lib of libs) {
        const url = `/public/openui5/${sapVersion}/${lib}`
        _pwaResources[url] = { url, cacheName: determineCacheNameFromUrl(url) };
    }

    const neptuneLibs = [
        '/socket.io/socket.io.js',
        '/public/neptune/external/bundle.js',
        '/public/neptune/external/bundle-dbg.js',
        '/public/neptune/p9library.js',
        '/public/neptune/p9library-dbg.js',
        '/public/neptune/aes.js',
        '/public/application/planet9_launchpad_standard/app.css'
    ];
    for (const url of neptuneLibs) {
        _pwaResources[url] = { url, cacheName: determineCacheNameFromUrl(url) };
    }

    // language files
    const supportedLanguages = {
        '1.71': [
            'en_NZ', 'fr_CH', 'pt', 'ar', 'en_PG', 'fr_LU', 'pt_PT', 'ar_EG', 'en_SG', 'he', 'ro', 
            'ar_SA', 'en_ZA', 'hi', 'ru', 'bg', 'es', 'hr', 'ru_UA', 'ca', 'es_AR', 'hu', 'sk', 'cs', 
            'es_BO', 'id', 'sl', 'da', 'es_CL', 'it', 'sr', 'de', 'es_CO', 'it_CH', 'sr_Latn', 
            'de_AT', 'es_MX', 'ja', 'sv', 'de_CH', 'es_PE', 'kk', 'th', 'el', 'es_UY', 'ko', 
            'tr', 'el_CY', 'es_VE', 'lt', 'uk', 'en', 'et', 'lv', 'vi', 'en_AU', 'fa', 'ms',
            'zh_CN', 'en_GB', 'fi', 'nb', 'zh_HK', 'en_HK', 'fr', 'nl', 'zh_SG', 'en_IE', 
            'fr_BE', 'nl_BE', 'zh_TW', 'en_IN', 'fr_CA', 'pl'
        ],
        '1.108': [
            'ar', 'da', 'en_AU', 'en_SG', 'es_MX', 'fr', 'hr', 'ko', 'pl', 'sl', 'vi', 'ar_EG',
            'de', 'en_GB', 'en_ZA', 'es_PE', 'fr_BE', 'hu', 'lt', 'pt', 'sr', 'zh_CN', 'ar_SA',
            'de_AT', 'en_HK', 'es', 'es_UY', 'fr_CA', 'id', 'lv', 'pt_PT', 'sr_Latn', 'zh_HK',
            'bg', 'de_CH', 'en_IE', 'es_AR', 'es_VE', 'fr_CH', 'it', 'ms', 'ro', 'sv', 'zh_SG',
            'ca', 'el', 'en_IN', 'es_BO', 'et', 'fr_LU', 'it_CH', 'nb', 'ru', 'th', 'zh_TW',
            'cs', 'el_CY', 'en_NZ', 'es_CL', 'fa', 'he', 'ja', 'nl', 'ru_UA', 'tr', 'cy',
            'en', 'en_PG', 'es_CO', 'fi', 'hi', 'kk', 'nl_BE', 'sk', 'uk'
        ],
    };

    const browserLanguage = navigator.language.replace('-', '_');
    const languages = ['en', 'en_GB'];
    if (supportedLanguages[sapVersion] && supportedLanguages[sapVersion].includes(browserLanguage)) {
        languages.push(browserLanguage);
    }

    if (Array.isArray(AppCache.config.languages)) {
        for (const lang of AppCache.config.languages) {
            if (supportedLanguages[sapVersion] && supportedLanguages[sapVersion].includes(lang.toLowerCase())) {
                languages.push(lang.toLowerCase());
            }
        }
    }

    if (sapVersion == '1.71') {
        const localdataUrl = `/public/openui5/${sapVersion}/sap/ui/core/LocaleData.js`;
        _pwaResources[localdataUrl] = { url: localdataUrl, cacheName: determineCacheNameFromUrl(localdataUrl) };    
        
        const libraryPreloadUrl = `/public/openui5/${sapVersion}/sap/ui/core/library-preload.js`;
        _pwaResources[libraryPreloadUrl] = { url: libraryPreloadUrl, cacheName: determineCacheNameFromUrl(libraryPreloadUrl) };    
    }

    for (const lang of languages) {
        const cldrUrl = `/public/openui5/${sapVersion}/sap/ui/core/cldr/${lang}.json`;
        _pwaResources[cldrUrl] = { url: cldrUrl, cacheName: determineCacheNameFromUrl(cldrUrl) };

        const messageProps = availableMessageProps[sapVersion] ?? [];
        for (const file of messageProps) {
            const parts = file.split('/');
            const fileName = parts[parts.length-1];
            if (fileName === 'messagebundle' || fileName.includes(`_${lang}`)) {
                const url = `/public/openui5/${sapVersion}/sap/${file}.properties`;
                _pwaResources[url] = { url, cacheName: determineCacheNameFromUrl(url) };
            }
        }

        const thirdParty = thirdpartyWebComponentsCldr[sapVersion] ?? [];
        for (const file of thirdParty) {
            if (file.startsWith(`${lang}-`)) {
                const url = `/public/openui5/${sapVersion}/sap/ui/integration/thirdparty/webcomponents/${file}`
                _pwaResources[url] = { url, cacheName: determineCacheNameFromUrl(url) };
            }
        }
    }

    if (window && window.performance && window.performance.getEntriesByType) {
        const resources = window.performance.getEntriesByType("resource").map(r => r.name);
        const allowedExts = [
            'js', 'json',   // scripts, data
            'properties',   // translations
            'gif', 'jpeg', 'jpg', 'png', 'svg', 'webp', // images
            'woff', 'woff2', // fonts
            'css', // stylesheets
        ];
        resources
            .filter(url => endsWith(url, allowedExts))
            .forEach(url => (_pwaResources[url] = { url, cacheName: determineCacheNameFromUrl(url) }));

        const allowedApi = [
            '/user/logon/types',
        ];
        resources
            .filter(url => endsWith(url, allowedApi))
            .forEach(url => (_pwaResources[url] = { url, cacheName: determineCacheNameFromUrl(url) }));
    }
}

function ensurePWACache() {
    if (!isPWAEnabled()) return;

    appCacheLog('ensure these pwa resources are available in cache', Object.keys(_pwaResources));

    Object.values(_pwaResources).forEach(async ({ url, cacheName }) => {
        const params = { url, cacheName };
        if (await isUrlInCache(params)) {
            appCacheLog(url, 'already exists in cache');
        } else {
            await addUrlToCache({ url, cacheName });
        }
    });
}

function emptyBase64Image() {
    return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAoMBgDTD2qgAAAAASUVORK5CYII=';
}

const _imagesCache = {}
const _lazyLoadImagesList = [];
let lazyLoadImagesInProgress = false;
function lazyLoadImage(src, target, type) {
    _lazyLoadImagesList.push({ src, target, type });
}

function downloadLazyLoadImages() {
    if (lazyLoadImagesInProgress || _lazyLoadImagesList.length === 0) {
        return;
    }

    lazyLoadImagesInProgress = true;

    function setImageSrc(src, target, type) {
        if (type === 'element' && target instanceof HTMLImageElement) {
            target.setAttribute('src', src);
        } else if (type === 'sap-component') {
            target.setSrc(src);
        } else if (type === 'style') {
            appendStyle(
                elById('NeptuneStyleDivDynamic'),
                createStyle(`
                    ${target} {
                        background-image: url(${src});
                    }
                `)
            );
        }
    }

    const { src, target, type } = _lazyLoadImagesList.shift();

    if (typeof _imagesCache[src] !== 'undefined') {
        setImageSrc(_imagesCache[src], target, type);
        lazyLoadImagesInProgress = false;
        downloadLazyLoadImages();
        return;
    }

    // for some reason, if src, target is undefined
    if (typeof src === 'undefined' || typeof target === 'undefined') {
        lazyLoadImagesInProgress = false;
        downloadLazyLoadImages();
        return;
    }

    if (src.startsWith('data:') || src.startsWith('blob:')) {
        setImageSrc(src, target, type);
        lazyLoadImagesInProgress = false;
        downloadLazyLoadImages();
        return;
    }

    // set blob url's directly, otherwise domains have be explicitly
    //  added to Azure Blob Storage to prevent CORS errors on fetch
    if (src.includes('blob.core.windows.net')) {
        setImageSrc(src, target, type);
        downloadLazyLoadImages();
        return;
    }

    fetch(src).then(res => {
        if (!res.ok) return;
        return res.blob();
    }).then(res => {
        _imagesCache[src] = URL.createObjectURL(res);
        setImageSrc(_imagesCache[src], target, type);
        lazyLoadImagesInProgress = false;
        downloadLazyLoadImages();
    }).catch(() => {
        lazyLoadImagesInProgress = false;
        downloadLazyLoadImages();
    });
}
